[package]
name = "link_informant"
version = "0.1.0"
edition = "2018"

[dependencies]
bufstream = "0.1.4"
reqwest = { version = "0.11.3", features = ["json", "blocking"] }
serde = { version = "1.0", features = ["derive"] }
config = "0.10.1"
select = "0.5.0"
linkify = "0.7.0"
